run_opa_tests:
  stage: test
  image:
    name: ubuntu:22.04
  script:
    - apt update -y && apt install -y curl
    - curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/v0.61.0/opa_linux_amd64
    - chmod 755 opa
    - ./opa test assets/opa/policy -v

