version: "3.7"

services:

  opa:
    image: openpolicyagent/opa:latest-debug
    ports:
      - "8181:8181"
    
    volumes:
      - ./assets/opa:/opa-examples
      - ./opa:/etc/opa
    
    entrypoint: opa run --server /etc/opa --log-level debug -c /etc/opa/config.yaml

    init: true
