saml:
  entity-id: ${IAM_SAML_ENTITY_ID}
  keystore: classpath:/saml/samlKeystore.jks
  keystore-password: password
  key-id: iam
  key-password: password

  local-metadata:
    generated: false
    location-url: classpath:/saml/iam.local.io.metadata.xml