server:
  address: ${VOMS_AA_HOST:localhost}
  port: ${VOMS_AA_PORT:15000}
  use-forward-headers: true

spring:
  main:
    banner-mode: "off"
    allow-circular-references: true

  flyway:
    table: schema_version
  
  jpa:
    open-in-view: false
      
voms:
  tls:
    certificate-path: /etc/grid-security/voms/hostcert.pem
    private-key-path: /etc/grid-security/voms/hostkey.pem
    trust-anchors-dir: /etc/grid-security/certificates
    trust-anchors-refresh-interval-secs: 14400
  aa:
    host: ${server.address}
    port: ${server.port}
    vo-name: ${VOMS_AA_VO:test}
    optional-group-label: voms.role
    use-legacy-fqan-encoding: false
